---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-prometheus-example
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet-prometheus-example
    spec:
      containers:
      - name: dotnet-prometheus-example
        image: quay.io/brice/dotnet-prometheus-example:d0a2de0613b0fb03b1e116033611bd37c1a742e0
        ports:
        - containerPort: 80
