apiVersion: v1
kind: Service
metadata:
  name: dotnet-prometheus-example
spec:
  type: NodePort
  selector:
    app: dotnet-prometheus-example
  ports:
    - port: 80
      name: http
      targetPort: 80
      nodePort: 30003
